# Generated by Django 6.0.5 on 2026-05-30 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Friendly name, e.g. 'Main Zerodha'.", max_length=100)),
                ('broker', models.CharField(choices=[('zerodha', 'Zerodha')], default='zerodha', max_length=20)),
                ('role', models.CharField(choices=[('master', 'Master'), ('copy', 'Copy')], max_length=10)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('api_secret', models.CharField(blank=True, max_length=200)),
                ('access_token', models.CharField(blank=True, max_length=500)),
                ('token_updated_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mismatch', 'Position mismatch'), ('order_failed', 'Copy order failed'), ('zero_qty', 'Zero quantity skipped'), ('token_expired', 'Access token expired')], max_length=20)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='copytrading.brokeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=4, default=1, help_text='copy_qty = round_to_lot(master_qty x multiplier).', max_digits=8)),
                ('zero_qty_policy', models.CharField(choices=[('skip_alert', 'Skip and alert'), ('skip_silent', 'Skip silently'), ('round_up', 'Round up to 1 lot')], default='skip_alert', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy', models.ForeignKey(limit_choices_to={'role': 'copy'}, on_delete=django.db.models.deletion.CASCADE, related_name='copy_mappings_as_copy', to='copytrading.brokeraccount')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='copy_mappings_as_master', to='copytrading.brokeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=10)),
                ('net_quantity', models.IntegerField()),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to='copytrading.brokeraccount')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(help_text='NSE/NFO/BSE/MCX/CDS', max_length=10)),
                ('instrument_token', models.BigIntegerField(blank=True, null=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('product', models.CharField(blank=True, help_text='MIS/NRML/CNC', max_length=10)),
                ('order_type', models.CharField(blank=True, help_text='MARKET/LIMIT/SL/SL-M', max_length=10)),
                ('broker_order_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='copytrading.brokeraccount')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('broker_order_id', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_kind', models.CharField(blank=True, choices=[('transient', 'Transient (retry)'), ('terminal', 'Terminal (no retry)')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_orders', to='copytrading.copymapping')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_orders', to='copytrading.trade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='copymapping',
            constraint=models.UniqueConstraint(fields=('master', 'copy'), name='uniq_master_copy'),
        ),
        migrations.AddIndex(
            model_name='positionsnapshot',
            index=models.Index(fields=['account', 'tradingsymbol', 'captured_at'], name='copytrading_account_f2ec10_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'broker_order_id'], name='copytrading_account_f7a2df_idx'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(condition=models.Q(('broker_order_id', ''), _negated=True), fields=('account', 'broker_order_id'), name='uniq_account_broker_order'),
        ),
    ]
