# Generated by Django 6.0.5 on 2026-05-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('zerodha', 'Zerodha')], default='zerodha', max_length=20)),
                ('exchange', models.CharField(max_length=10)),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('instrument_token', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('lot_size', models.PositiveIntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('instrument_type', models.CharField(blank=True, help_text='FUT/CE/PE/EQ', max_length=10)),
                ('segment', models.CharField(blank=True, max_length=20)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-last_seen_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alert',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['kind', 'dedup_key', 'resolved'], name='copytrading_kind_74573d_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['exchange', 'tradingsymbol'], name='copytrading_exchang_1acc47_idx'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('broker', 'exchange', 'tradingsymbol'), name='uniq_instrument'),
        ),
    ]
