# Generated by Django 6.0.5 on 2026-05-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrading', '0002_instrument_alter_alert_options_alert_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='copy_orders_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copyorder',
            name='is_dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='trigger_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='variety',
            field=models.CharField(blank=True, default='regular', max_length=15),
        ),
        migrations.AlterField(
            model_name='copyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('simulated', 'Simulated (dry-run)')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='copyorder',
            constraint=models.UniqueConstraint(fields=('trade', 'mapping'), name='uniq_trade_mapping'),
        ),
    ]
